version: '3'

services:
  laravel_franken:
    container_name: laravel_franken
    image: image_laravel_franken
    build: .
    ports:
      - "8001:80"
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:6cEySynNymTz1NLuZH93U0nG0dRHyvI6Xwmq+86uaNc=
      APP_DEBUG: "true"
      APP_URL: http://localhost
      DB_CONNECTION: sqlite